### ISSUE TITLE
Experiment-metadata: allow `nominal_resolution` field to be an array or a string

### ISSUE THREAD

**Issue by jo-basevi** [ACCESS-NRI/schema#18]
The `nominal_resolution` field is currently an array in the experiment-metadata [schema](https://github.com/ACCESS-NRI/schema/blob/e9055da95093ec2faa555c090fc5af17923d1566/au.org.access-nri/model/output/experiment-metadata/1-0-2.json#L106-L110)

As ACCESS-OM2 configs (in [access-om2-configs](https://github.com/ACCESS-NRI/access-om2-configs/blob/8f901c68fef84e90ccdf9ece4deeddc6ddc2c8dd/CONTRIBUTING.md?plain=1#L100-L110)) have one `nominal_resolution`, similarly to the `model` field (https://github.com/ACCESS-NRI/schema/issues/11), we could allow the field to be a string or an array.

**Comment by aidanheerdegen** [comment]
Any thoughts @dougiesquire?

**Comment by dougiesquire** [comment]
Sounds good to me!
