### ISSUE TITLE
Model datatype in intake metadata

### ISSUE THREAD

**Issue by utkarshgupta95** [ACCESS-NRI/schema#9]
@dougiesquire The model datatype in intake metadata is an array but experiments I have seen so far contains only one entry "ACCESS-OM2" in that array. Is that intentional or are there component models missing?

**Comment by dougiesquire** [comment]
Hi @utkarshgupta95. Yes that's correct. An experiment might contain multiple models, but atm most in the access-nri intake catalog contain only one. I think the CMIP entries are the only exception at the moment - these contain many models.

**Comment by utkarshgupta95** [comment]
Thanks for explanation
